name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout master
      uses: actions/checkout@v1
      with:
        submodules: true

    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.75.1
        TARGET_REPO: malmans2/malmans2.github.io
        TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        CNAME: malmans2.github.io
