name: github pages

on:
  push:
    branches:
      - master  # Set a branch name to trigger deployment

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up
        uses: actions/checkout@v2
        uses: actions/setup-go@v2

      - name: Install hugo
        run: |
            wget -O hugo_install.deb https://github.com/gohugoio/hugo/releases/download/v0.76.5/hugo_extended_0.76.5_Linux-64bit.deb
            sudo dpkg -i hugo_install.deb
      
      - name: Clone previus built
        run: |
            git clone https://github.com/malmans2/malmans2.github.io.git public
            cd public
            git checkout -b test
            cd ..

      - name: Build
        run: |
            hugo
            cd public

      - name: Push
        env:
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
            git remote set-url --push origin https://malmans2:$DEPLOY_TOKEN@github.com/malmans2/malmans2.github.io
            git push -u origin test
        
