name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2

      - name: Install hugo
        run: |
            HUGO_VERSION=$(grep -i HUGO_VERSION netlify.toml | sed 's/ //g' | sed 's/.*=//g' | sed 's/"//g')
            wget -O hugo_install.deb https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_Linux-64bit.deb
            sudo dpkg -i hugo_install.deb
      
      - name: Clone previus built
        env:
            GITHUB_USER: ${{ github.actor }}
        run: |
            git clone https://github.com/${GITHUB_USER}/${GITHUB_USER}.github.io.git public

      - name: Build
        run: |
            hugo --gc --minify -b https://malmans2.github.io/
            cd public

      - name: Push
        env:
            GITHUB_USER: ${{ github.actor }}
            DEPLOY_TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        run: |
            cd public
            git remote set-url --push origin https://${GITHUB_USER}:$DEPLOY_TOKEN@github.com/${GITHUB_USER}/${GITHUB_USER}.github.io
            git config --global user.name $GITHUB_USER
            git add .
            git commit -m "Automatic deployment"
            git push -u origin master
        
