name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: snap install --classic go


    - name: Hugo Deploy GitHub Pages
      uses: benmatselby/hugo-deploy-gh-pages@master
      env:
        HUGO_VERSION: 0.73.0
        HUGO_EXTENDED: true
        TARGET_REPO: malmans2/malmans2.github.io
        TOKEN: ${{ secrets.DEPLOY_TOKEN }}
        CNAME: malmans2.github.io
